# UNCOMMENT THESE DROP statements TO RE-RUN THIS SCRIPT


#drop table STUDENT;
#drop table FACULTY;
#drop table MENTOR;
#drop table ALUMNI;
#drop table ASSIGNMENT;
#drop table STUD_MNTR;
#drop table FCTLY_MNTR;

CREATE TABLE STUDENT (
    Student_ID INT NOT NULL AUTO_INCREMENT,
    LastName CHAR(25) NOT NULL,
    FirstName CHAR(25) NOT NULL,
    EmailAddress VARCHAR(100) NOT NULL,
    DormName CHAR(25) NOT NULL,
    DormRmNumber CHAR(10) NOT NULL,
    DormRmPhone CHAR(14) NOT NULL,
    EnrollDate DATE NOT NULL,
    GradDate DATE NOT NULL,
    DegreeType CHAR(25) NOT NULL,
    CONSTRAINT Student_PK PRIMARY KEY (Student_ID)
);
ALTER TABLE STUDENT AUTO_INCREMENT = 1000;

CREATE TABLE FACULTY (
    Faculty_ID INT NOT NULL AUTO_INCREMENT,
    LastName CHAR(25) NOT NULL,
    FirstName CHAR(25) NOT NULL,
    EmailAddress VARCHAR(100) NOT NULL,
    Department CHAR(25) NOT NULL,
    OfficeName CHAR(25) NOT NULL,
    OfficeRmNumber CHAR(10) NOT NULL,
    OfficePnNumber CHAR(14) NOT NULL,
    CONSTRAINT Faculty_PK PRIMARY KEY (Faculty_ID)
);
ALTER TABLE FACULTY AUTO_INCREMENT = 2000;

CREATE TABLE MENTOR (
    Mentor_ID INT NOT NULL AUTO_INCREMENT,
    LastName CHAR(25) NOT NULL,
    FirstName CHAR(25) NOT NULL,
    EmailAddress VARCHAR(100) NOT NULL,
    CompanyName CHAR(25) NOT NULL,
    CompanyZip CHAR(5) NULL,
    CompanyAddress CHAR(50) NULL,
    CompanyCity CHAR(25) NULL,
    CompanyState CHAR(2) NULL,
    CompanyPnNumber CHAR(14) NOT NULL,
    CONSTRAINT Mentor_PK PRIMARY KEY (Mentor_ID)
);
ALTER TABLE MENTOR AUTO_INCREMENT = 3000;

CREATE TABLE ALUMNI (
    AlumniStudent_ID INT NOT NULL AUTO_INCREMENT,
    Mentor_ID INT NULL,
    LastName CHAR(25) NOT NULL,
    FirstName CHAR(25) NOT NULL,
    EmailAddress VARCHAR(100) NOT NULL,
    Address CHAR(50) NOT NULL,
    City CHAR(25) NOT NULL,
    State CHAR(2) NOT NULL,
    Zip CHAR(5) NOT NULL,
    PhoneNumber CHAR(14) NOT NULL,
    CONSTRAINT ALUMNI PRIMARY KEY (AlumniStudent_ID),
    CONSTRAINT MENTOR FOREIGN KEY (Mentor_ID)
        REFERENCES MENTOR (Mentor_ID),
    CONSTRAINT ALUMNI_MENTOR UNIQUE (Mentor_ID)
);
ALTER TABLE ALUMNI AUTO_INCREMENT = 4000;

CREATE TABLE ASSIGNMENT (
    Student_ID INT NOT NULL,
    Faculty_ID INT NOT NULL,
    StartDate DATE NOT NULL,
    EndDate DATE NOT NULL,
    CONSTRAINT S_F_PK PRIMARY KEY (Student_ID , Faculty_ID),
    CONSTRAINT S_F_Student_FK FOREIGN KEY (Student_ID)
        REFERENCES STUDENT (Student_ID)
        ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT S_F_Faculty_FK FOREIGN KEY (Faculty_ID)
        REFERENCES FACULTY (Faculty_ID)
        ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE STUD_MNTR (
    Student_ID INT NOT NULL,
    Mentor_ID INT NOT NULL,
    StartDate DATE NOT NULL,
    EndDate DATE NOT NULL,
    CONSTRAINT S_M_PK PRIMARY KEY (Student_ID , Mentor_ID),
    CONSTRAINT S_M_Student_FK FOREIGN KEY (Student_ID)
        REFERENCES STUDENT (Student_ID)
        ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT S_M_Mentor_FK FOREIGN KEY (Mentor_ID)
        REFERENCES MENTOR (Mentor_ID)
        ON DELETE NO ACTION ON UPDATE NO ACTION
);


CREATE TABLE FCTLY_MNTR (
    Faculty_ID INT NOT NULL,
    Mentor_ID INT NOT NULL,
    StartDate DATE NOT NULL,
    EndDate DATE NOT NULL,
    CONSTRAINT F_M_PK PRIMARY KEY (Faculty_ID , Mentor_ID),
    CONSTRAINT F_M_Faculty_FK FOREIGN KEY (Faculty_ID)
        REFERENCES FACULTY (Faculty_ID)
        ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT F_M_Mentor_FK FOREIGN KEY (Mentor_ID)
        REFERENCES MENTOR (Mentor_ID)
        ON DELETE NO ACTION ON UPDATE NO ACTION
);
